/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminProfilePure { 'name' : string }
export type AdmissionNumber = string;
export type ClassName = string;
export interface ClassStats { 'className' : ClassName, 'studentCount' : bigint }
export interface ClassWiseFeesExportRecord {
  'paymentStatus' : boolean,
  'studentName' : string,
  'feeMonth' : Month,
  'completeAddress' : string,
  'parentContactNumber' : string,
  'motherName' : string,
  'admissionNumber' : AdmissionNumber,
  'amountPaid' : bigint,
  'fatherName' : string,
  'className' : ClassName,
}
export type ExternalBlob = Uint8Array;
export interface FeeExportRecord {
  'month' : Month,
  'paymentStatus' : boolean,
  'studentName' : string,
  'completeAddress' : string,
  'parentContactNumber' : string,
  'feeType' : string,
  'motherName' : string,
  'admissionNumber' : AdmissionNumber,
  'amountPaid' : bigint,
  'fatherName' : string,
  'paymentDate' : [] | [string],
  'paymentMode' : [] | [string],
  'className' : ClassName,
}
export interface FeeRecordPure {
  'paidMonths' : Array<Month>,
  'studentAdmission' : StudentAdmissionPure,
  'monthlyPayments' : MonthlyPaymentPure,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Month = string;
export interface MonthlyPaymentPure {
  'may' : bigint,
  'march' : bigint,
  'april' : bigint,
  'november' : bigint,
  'july' : bigint,
  'june' : bigint,
  'february' : bigint,
  'september' : bigint,
  'august' : bigint,
  'january' : bigint,
  'october' : bigint,
  'december' : bigint,
}
export interface MonthlyPayments {
  'may' : bigint,
  'march' : bigint,
  'april' : bigint,
  'november' : bigint,
  'july' : bigint,
  'june' : bigint,
  'february' : bigint,
  'september' : bigint,
  'august' : bigint,
  'january' : bigint,
  'october' : bigint,
  'december' : bigint,
}
export interface PendingFeeRecord {
  'month' : Month,
  'paymentStatus' : boolean,
  'studentName' : string,
  'admissionNumber' : AdmissionNumber,
  'className' : ClassName,
}
export interface StaffProfilePure { 'assignedClasses' : Array<ClassName> }
export interface StudentAdmissionPersist {
  'studentName' : string,
  'dateOfBirth' : Time,
  'admissionDate' : Time,
  'isFreeStudent' : boolean,
  'motherName' : string,
  'admissionNumber' : AdmissionNumber,
  'fatherName' : string,
  'admittedClass' : ClassName,
  'address' : string,
  'gender' : Gender,
  'admissionAmount' : bigint,
  'fatherAadhaarNumber' : string,
  'aadhaarNumber' : string,
  'photo' : [] | [ExternalBlob],
  'phoneNumber' : string,
  'motherAadhaarNumber' : string,
}
export interface StudentAdmissionPure {
  'studentName' : string,
  'dateOfBirth' : Time,
  'admissionDate' : Time,
  'isFreeStudent' : boolean,
  'motherName' : string,
  'admissionNumber' : AdmissionNumber,
  'fatherName' : string,
  'admittedClass' : ClassName,
  'address' : string,
  'gender' : Gender,
  'admissionAmount' : bigint,
  'fatherAadhaarNumber' : string,
  'aadhaarNumber' : string,
  'photo' : [] | [ExternalBlob],
  'phoneNumber' : string,
  'motherAadhaarNumber' : string,
}
export type Time = bigint;
export interface TotalAmountRecord {
  'grandTotal' : bigint,
  'admissionFeesTotal' : bigint,
  'className' : ClassName,
  'monthlyFeesTotal' : bigint,
}
export type UserProfilePure = { 'admin' : AdminProfilePure } |
  { 'staff' : StaffProfilePure };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addAdmissionRecord' : ActorMethod<[StudentAdmissionPure], AdmissionNumber>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStaffAccount' : ActorMethod<[Principal, Array<ClassName>], undefined>,
  'deleteStudentRecord' : ActorMethod<[AdmissionNumber], undefined>,
  'getAdmission' : ActorMethod<[AdmissionNumber], StudentAdmissionPure>,
  'getAllFeesData' : ActorMethod<[], Array<FeeExportRecord>>,
  'getAllStudentData' : ActorMethod<[], Array<StudentAdmissionPersist>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePure]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClassAdmissions' : ActorMethod<[ClassName], Array<StudentAdmissionPure>>,
  'getClassFeesData' : ActorMethod<[ClassName], Array<FeeExportRecord>>,
  'getClassStudentData' : ActorMethod<
    [ClassName],
    Array<StudentAdmissionPersist>
  >,
  'getClassWiseFeesData' : ActorMethod<
    [ClassName],
    Array<ClassWiseFeesExportRecord>
  >,
  'getFeeStatus' : ActorMethod<[ClassName], Array<FeeRecordPure>>,
  'getFreeStudentsData' : ActorMethod<[], Array<StudentAdmissionPersist>>,
  'getGenderOptions' : ActorMethod<[], Array<Gender>>,
  'getMonthlyFeeAlerts' : ActorMethod<[], Array<PendingFeeRecord>>,
  'getPendingFeesReport' : ActorMethod<
    [Month, [] | [ClassName]],
    Array<PendingFeeRecord>
  >,
  'getPredefinedClassOptions' : ActorMethod<[], Array<ClassName>>,
  'getStudentFeeRecord' : ActorMethod<[AdmissionNumber], FeeRecordPure>,
  'getStudentStatsByClass' : ActorMethod<
    [],
    { 'totalStudents' : bigint, 'classStats' : Array<ClassStats> }
  >,
  'getTotalAmountCollection' : ActorMethod<
    [],
    {
      'grandTotals' : TotalAmountRecord,
      'classTotals' : Array<TotalAmountRecord>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePure]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMonthPaid' : ActorMethod<[AdmissionNumber, Month], undefined>,
  'markMonthlyPayments' : ActorMethod<
    [AdmissionNumber, MonthlyPayments],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfilePure], undefined>,
  'searchStudent' : ActorMethod<[string], Array<StudentAdmissionPure>>,
  'updateStudentRecord' : ActorMethod<
    [AdmissionNumber, StudentAdmissionPure],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];