/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AdmissionNumber = IDL.Text;
export const ClassName = IDL.Text;
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StudentAdmissionPure = IDL.Record({
  'studentName' : IDL.Text,
  'dateOfBirth' : Time,
  'admissionDate' : Time,
  'isFreeStudent' : IDL.Bool,
  'motherName' : IDL.Text,
  'admissionNumber' : AdmissionNumber,
  'fatherName' : IDL.Text,
  'admittedClass' : ClassName,
  'address' : IDL.Text,
  'gender' : Gender,
  'admissionAmount' : IDL.Nat,
  'fatherAadhaarNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Text,
  'motherAadhaarNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Month = IDL.Text;
export const FeeExportRecord = IDL.Record({
  'month' : Month,
  'paymentStatus' : IDL.Bool,
  'studentName' : IDL.Text,
  'completeAddress' : IDL.Text,
  'parentContactNumber' : IDL.Text,
  'feeType' : IDL.Text,
  'motherName' : IDL.Text,
  'admissionNumber' : AdmissionNumber,
  'amountPaid' : IDL.Nat,
  'fatherName' : IDL.Text,
  'paymentDate' : IDL.Opt(IDL.Text),
  'paymentMode' : IDL.Opt(IDL.Text),
  'className' : ClassName,
});
export const StudentAdmissionPersist = IDL.Record({
  'studentName' : IDL.Text,
  'dateOfBirth' : Time,
  'admissionDate' : Time,
  'isFreeStudent' : IDL.Bool,
  'motherName' : IDL.Text,
  'admissionNumber' : AdmissionNumber,
  'fatherName' : IDL.Text,
  'admittedClass' : ClassName,
  'address' : IDL.Text,
  'gender' : Gender,
  'admissionAmount' : IDL.Nat,
  'fatherAadhaarNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'phoneNumber' : IDL.Text,
  'motherAadhaarNumber' : IDL.Text,
});
export const AdminProfilePure = IDL.Record({ 'name' : IDL.Text });
export const StaffProfilePure = IDL.Record({
  'assignedClasses' : IDL.Vec(ClassName),
});
export const UserProfilePure = IDL.Variant({
  'admin' : AdminProfilePure,
  'staff' : StaffProfilePure,
});
export const ClassWiseFeesExportRecord = IDL.Record({
  'paymentStatus' : IDL.Bool,
  'studentName' : IDL.Text,
  'feeMonth' : Month,
  'completeAddress' : IDL.Text,
  'parentContactNumber' : IDL.Text,
  'motherName' : IDL.Text,
  'admissionNumber' : AdmissionNumber,
  'amountPaid' : IDL.Nat,
  'fatherName' : IDL.Text,
  'className' : ClassName,
});
export const MonthlyPaymentPure = IDL.Record({
  'may' : IDL.Nat,
  'march' : IDL.Nat,
  'april' : IDL.Nat,
  'november' : IDL.Nat,
  'july' : IDL.Nat,
  'june' : IDL.Nat,
  'february' : IDL.Nat,
  'september' : IDL.Nat,
  'august' : IDL.Nat,
  'january' : IDL.Nat,
  'october' : IDL.Nat,
  'december' : IDL.Nat,
});
export const FeeRecordPure = IDL.Record({
  'paidMonths' : IDL.Vec(Month),
  'studentAdmission' : StudentAdmissionPure,
  'monthlyPayments' : MonthlyPaymentPure,
});
export const PendingFeeRecord = IDL.Record({
  'month' : Month,
  'paymentStatus' : IDL.Bool,
  'studentName' : IDL.Text,
  'admissionNumber' : AdmissionNumber,
  'className' : ClassName,
});
export const ClassStats = IDL.Record({
  'className' : ClassName,
  'studentCount' : IDL.Nat,
});
export const TotalAmountRecord = IDL.Record({
  'grandTotal' : IDL.Nat,
  'admissionFeesTotal' : IDL.Nat,
  'className' : ClassName,
  'monthlyFeesTotal' : IDL.Nat,
});
export const MonthlyPayments = IDL.Record({
  'may' : IDL.Nat,
  'march' : IDL.Nat,
  'april' : IDL.Nat,
  'november' : IDL.Nat,
  'july' : IDL.Nat,
  'june' : IDL.Nat,
  'february' : IDL.Nat,
  'september' : IDL.Nat,
  'august' : IDL.Nat,
  'january' : IDL.Nat,
  'october' : IDL.Nat,
  'december' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAdmissionRecord' : IDL.Func(
      [StudentAdmissionPure],
      [AdmissionNumber],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStaffAccount' : IDL.Func([IDL.Principal, IDL.Vec(ClassName)], [], []),
  'deleteStudentRecord' : IDL.Func([AdmissionNumber], [], []),
  'getAdmission' : IDL.Func(
      [AdmissionNumber],
      [StudentAdmissionPure],
      ['query'],
    ),
  'getAllFeesData' : IDL.Func([], [IDL.Vec(FeeExportRecord)], []),
  'getAllStudentData' : IDL.Func(
      [],
      [IDL.Vec(StudentAdmissionPersist)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePure)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClassAdmissions' : IDL.Func(
      [ClassName],
      [IDL.Vec(StudentAdmissionPure)],
      ['query'],
    ),
  'getClassFeesData' : IDL.Func([ClassName], [IDL.Vec(FeeExportRecord)], []),
  'getClassStudentData' : IDL.Func(
      [ClassName],
      [IDL.Vec(StudentAdmissionPersist)],
      ['query'],
    ),
  'getClassWiseFeesData' : IDL.Func(
      [ClassName],
      [IDL.Vec(ClassWiseFeesExportRecord)],
      [],
    ),
  'getFeeStatus' : IDL.Func([ClassName], [IDL.Vec(FeeRecordPure)], ['query']),
  'getFreeStudentsData' : IDL.Func(
      [],
      [IDL.Vec(StudentAdmissionPersist)],
      ['query'],
    ),
  'getGenderOptions' : IDL.Func([], [IDL.Vec(Gender)], ['query']),
  'getMonthlyFeeAlerts' : IDL.Func([], [IDL.Vec(PendingFeeRecord)], ['query']),
  'getPendingFeesReport' : IDL.Func(
      [Month, IDL.Opt(ClassName)],
      [IDL.Vec(PendingFeeRecord)],
      ['query'],
    ),
  'getPredefinedClassOptions' : IDL.Func([], [IDL.Vec(ClassName)], ['query']),
  'getStudentFeeRecord' : IDL.Func(
      [AdmissionNumber],
      [FeeRecordPure],
      ['query'],
    ),
  'getStudentStatsByClass' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalStudents' : IDL.Nat,
          'classStats' : IDL.Vec(ClassStats),
        }),
      ],
      ['query'],
    ),
  'getTotalAmountCollection' : IDL.Func(
      [],
      [
        IDL.Record({
          'grandTotals' : TotalAmountRecord,
          'classTotals' : IDL.Vec(TotalAmountRecord),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePure)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMonthPaid' : IDL.Func([AdmissionNumber, Month], [], []),
  'markMonthlyPayments' : IDL.Func([AdmissionNumber, MonthlyPayments], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfilePure], [], []),
  'searchStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentAdmissionPure)],
      ['query'],
    ),
  'updateStudentRecord' : IDL.Func(
      [AdmissionNumber, StudentAdmissionPure],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AdmissionNumber = IDL.Text;
  const ClassName = IDL.Text;
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StudentAdmissionPure = IDL.Record({
    'studentName' : IDL.Text,
    'dateOfBirth' : Time,
    'admissionDate' : Time,
    'isFreeStudent' : IDL.Bool,
    'motherName' : IDL.Text,
    'admissionNumber' : AdmissionNumber,
    'fatherName' : IDL.Text,
    'admittedClass' : ClassName,
    'address' : IDL.Text,
    'gender' : Gender,
    'admissionAmount' : IDL.Nat,
    'fatherAadhaarNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Text,
    'motherAadhaarNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Month = IDL.Text;
  const FeeExportRecord = IDL.Record({
    'month' : Month,
    'paymentStatus' : IDL.Bool,
    'studentName' : IDL.Text,
    'completeAddress' : IDL.Text,
    'parentContactNumber' : IDL.Text,
    'feeType' : IDL.Text,
    'motherName' : IDL.Text,
    'admissionNumber' : AdmissionNumber,
    'amountPaid' : IDL.Nat,
    'fatherName' : IDL.Text,
    'paymentDate' : IDL.Opt(IDL.Text),
    'paymentMode' : IDL.Opt(IDL.Text),
    'className' : ClassName,
  });
  const StudentAdmissionPersist = IDL.Record({
    'studentName' : IDL.Text,
    'dateOfBirth' : Time,
    'admissionDate' : Time,
    'isFreeStudent' : IDL.Bool,
    'motherName' : IDL.Text,
    'admissionNumber' : AdmissionNumber,
    'fatherName' : IDL.Text,
    'admittedClass' : ClassName,
    'address' : IDL.Text,
    'gender' : Gender,
    'admissionAmount' : IDL.Nat,
    'fatherAadhaarNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'phoneNumber' : IDL.Text,
    'motherAadhaarNumber' : IDL.Text,
  });
  const AdminProfilePure = IDL.Record({ 'name' : IDL.Text });
  const StaffProfilePure = IDL.Record({
    'assignedClasses' : IDL.Vec(ClassName),
  });
  const UserProfilePure = IDL.Variant({
    'admin' : AdminProfilePure,
    'staff' : StaffProfilePure,
  });
  const ClassWiseFeesExportRecord = IDL.Record({
    'paymentStatus' : IDL.Bool,
    'studentName' : IDL.Text,
    'feeMonth' : Month,
    'completeAddress' : IDL.Text,
    'parentContactNumber' : IDL.Text,
    'motherName' : IDL.Text,
    'admissionNumber' : AdmissionNumber,
    'amountPaid' : IDL.Nat,
    'fatherName' : IDL.Text,
    'className' : ClassName,
  });
  const MonthlyPaymentPure = IDL.Record({
    'may' : IDL.Nat,
    'march' : IDL.Nat,
    'april' : IDL.Nat,
    'november' : IDL.Nat,
    'july' : IDL.Nat,
    'june' : IDL.Nat,
    'february' : IDL.Nat,
    'september' : IDL.Nat,
    'august' : IDL.Nat,
    'january' : IDL.Nat,
    'october' : IDL.Nat,
    'december' : IDL.Nat,
  });
  const FeeRecordPure = IDL.Record({
    'paidMonths' : IDL.Vec(Month),
    'studentAdmission' : StudentAdmissionPure,
    'monthlyPayments' : MonthlyPaymentPure,
  });
  const PendingFeeRecord = IDL.Record({
    'month' : Month,
    'paymentStatus' : IDL.Bool,
    'studentName' : IDL.Text,
    'admissionNumber' : AdmissionNumber,
    'className' : ClassName,
  });
  const ClassStats = IDL.Record({
    'className' : ClassName,
    'studentCount' : IDL.Nat,
  });
  const TotalAmountRecord = IDL.Record({
    'grandTotal' : IDL.Nat,
    'admissionFeesTotal' : IDL.Nat,
    'className' : ClassName,
    'monthlyFeesTotal' : IDL.Nat,
  });
  const MonthlyPayments = IDL.Record({
    'may' : IDL.Nat,
    'march' : IDL.Nat,
    'april' : IDL.Nat,
    'november' : IDL.Nat,
    'july' : IDL.Nat,
    'june' : IDL.Nat,
    'february' : IDL.Nat,
    'september' : IDL.Nat,
    'august' : IDL.Nat,
    'january' : IDL.Nat,
    'october' : IDL.Nat,
    'december' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAdmissionRecord' : IDL.Func(
        [StudentAdmissionPure],
        [AdmissionNumber],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStaffAccount' : IDL.Func(
        [IDL.Principal, IDL.Vec(ClassName)],
        [],
        [],
      ),
    'deleteStudentRecord' : IDL.Func([AdmissionNumber], [], []),
    'getAdmission' : IDL.Func(
        [AdmissionNumber],
        [StudentAdmissionPure],
        ['query'],
      ),
    'getAllFeesData' : IDL.Func([], [IDL.Vec(FeeExportRecord)], []),
    'getAllStudentData' : IDL.Func(
        [],
        [IDL.Vec(StudentAdmissionPersist)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePure)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClassAdmissions' : IDL.Func(
        [ClassName],
        [IDL.Vec(StudentAdmissionPure)],
        ['query'],
      ),
    'getClassFeesData' : IDL.Func([ClassName], [IDL.Vec(FeeExportRecord)], []),
    'getClassStudentData' : IDL.Func(
        [ClassName],
        [IDL.Vec(StudentAdmissionPersist)],
        ['query'],
      ),
    'getClassWiseFeesData' : IDL.Func(
        [ClassName],
        [IDL.Vec(ClassWiseFeesExportRecord)],
        [],
      ),
    'getFeeStatus' : IDL.Func([ClassName], [IDL.Vec(FeeRecordPure)], ['query']),
    'getFreeStudentsData' : IDL.Func(
        [],
        [IDL.Vec(StudentAdmissionPersist)],
        ['query'],
      ),
    'getGenderOptions' : IDL.Func([], [IDL.Vec(Gender)], ['query']),
    'getMonthlyFeeAlerts' : IDL.Func(
        [],
        [IDL.Vec(PendingFeeRecord)],
        ['query'],
      ),
    'getPendingFeesReport' : IDL.Func(
        [Month, IDL.Opt(ClassName)],
        [IDL.Vec(PendingFeeRecord)],
        ['query'],
      ),
    'getPredefinedClassOptions' : IDL.Func([], [IDL.Vec(ClassName)], ['query']),
    'getStudentFeeRecord' : IDL.Func(
        [AdmissionNumber],
        [FeeRecordPure],
        ['query'],
      ),
    'getStudentStatsByClass' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalStudents' : IDL.Nat,
            'classStats' : IDL.Vec(ClassStats),
          }),
        ],
        ['query'],
      ),
    'getTotalAmountCollection' : IDL.Func(
        [],
        [
          IDL.Record({
            'grandTotals' : TotalAmountRecord,
            'classTotals' : IDL.Vec(TotalAmountRecord),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePure)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMonthPaid' : IDL.Func([AdmissionNumber, Month], [], []),
    'markMonthlyPayments' : IDL.Func(
        [AdmissionNumber, MonthlyPayments],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfilePure], [], []),
    'searchStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentAdmissionPure)],
        ['query'],
      ),
    'updateStudentRecord' : IDL.Func(
        [AdmissionNumber, StudentAdmissionPure],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };