/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type ClassName = string;
export interface MonthlyPayments {
    may: bigint;
    march: bigint;
    april: bigint;
    november: bigint;
    july: bigint;
    june: bigint;
    february: bigint;
    september: bigint;
    august: bigint;
    january: bigint;
    october: bigint;
    december: bigint;
}
export interface MonthlyPaymentPure {
    may: bigint;
    march: bigint;
    april: bigint;
    november: bigint;
    july: bigint;
    june: bigint;
    february: bigint;
    september: bigint;
    august: bigint;
    january: bigint;
    october: bigint;
    december: bigint;
}
export interface AdminProfilePure {
    name: string;
}
export type Month = string;
export interface StudentAdmissionPure {
    studentName: string;
    dateOfBirth: Time;
    admissionDate: Time;
    isFreeStudent: boolean;
    motherName: string;
    admissionNumber: AdmissionNumber;
    fatherName: string;
    admittedClass: ClassName;
    address: string;
    gender: Gender;
    admissionAmount: bigint;
    fatherAadhaarNumber: string;
    aadhaarNumber: string;
    photo?: ExternalBlob;
    phoneNumber: string;
    motherAadhaarNumber: string;
}
export interface ClassWiseFeesExportRecord {
    paymentStatus: boolean;
    studentName: string;
    feeMonth: Month;
    completeAddress: string;
    parentContactNumber: string;
    motherName: string;
    admissionNumber: AdmissionNumber;
    amountPaid: bigint;
    fatherName: string;
    className: ClassName;
}
export type UserProfilePure = {
    __kind__: "admin";
    admin: AdminProfilePure;
} | {
    __kind__: "staff";
    staff: StaffProfilePure;
};
export interface PendingFeeRecord {
    month: Month;
    paymentStatus: boolean;
    studentName: string;
    admissionNumber: AdmissionNumber;
    className: ClassName;
}
export interface StudentAdmissionPersist {
    studentName: string;
    dateOfBirth: Time;
    admissionDate: Time;
    isFreeStudent: boolean;
    motherName: string;
    admissionNumber: AdmissionNumber;
    fatherName: string;
    admittedClass: ClassName;
    address: string;
    gender: Gender;
    admissionAmount: bigint;
    fatherAadhaarNumber: string;
    aadhaarNumber: string;
    photo?: ExternalBlob;
    phoneNumber: string;
    motherAadhaarNumber: string;
}
export interface FeeRecordPure {
    paidMonths: Array<Month>;
    studentAdmission: StudentAdmissionPure;
    monthlyPayments: MonthlyPaymentPure;
}
export interface FeeExportRecord {
    month: Month;
    paymentStatus: boolean;
    studentName: string;
    completeAddress: string;
    parentContactNumber: string;
    feeType: string;
    motherName: string;
    admissionNumber: AdmissionNumber;
    amountPaid: bigint;
    fatherName: string;
    paymentDate?: string;
    paymentMode?: string;
    className: ClassName;
}
export interface StaffProfilePure {
    assignedClasses: Array<ClassName>;
}
export interface ClassStats {
    className: ClassName;
    studentCount: bigint;
}
export type AdmissionNumber = string;
export interface TotalAmountRecord {
    grandTotal: bigint;
    admissionFeesTotal: bigint;
    className: ClassName;
    monthlyFeesTotal: bigint;
}
export interface ParentStudentInfo {
    studentName: string;
    fatherName: string;
    motherName: string;
    admittedClass: ClassName;
    gender: Gender;
    dateOfBirth: Time;
    address: string;
    phoneNumber: string;
    admissionDate: Time;
    admissionAmount: bigint;
    admissionNumber: AdmissionNumber;
    isFreeStudent: boolean;
    monthlyPayments: MonthlyPaymentPure;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addAdmissionRecord(admission: StudentAdmissionPure): Promise<AdmissionNumber>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createStaffAccount(staffPrincipal: Principal, assignedClasses: Array<ClassName>): Promise<void>;
    deleteStudentRecord(admissionNumber: AdmissionNumber): Promise<void>;
    getAdmission(admissionNumber: AdmissionNumber): Promise<StudentAdmissionPure>;
    getAllFeesData(): Promise<Array<FeeExportRecord>>;
    getAllStudentData(): Promise<Array<StudentAdmissionPersist>>;
    getCallerUserProfile(): Promise<UserProfilePure | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClassAdmissions(className: ClassName): Promise<Array<StudentAdmissionPure>>;
    getClassFeesData(className: ClassName): Promise<Array<FeeExportRecord>>;
    getClassStudentData(className: ClassName): Promise<Array<StudentAdmissionPersist>>;
    getClassWiseFeesData(className: ClassName): Promise<Array<ClassWiseFeesExportRecord>>;
    getFeeStatus(className: ClassName): Promise<Array<FeeRecordPure>>;
    getFreeStudentsData(): Promise<Array<StudentAdmissionPersist>>;
    getGenderOptions(): Promise<Array<Gender>>;
    getMonthlyFeeAlerts(): Promise<Array<PendingFeeRecord>>;
    getPendingFeesReport(month: Month, className: ClassName | null): Promise<Array<PendingFeeRecord>>;
    getPredefinedClassOptions(): Promise<Array<ClassName>>;
    getStudentFeeRecord(admissionNumber: AdmissionNumber): Promise<FeeRecordPure>;
    getStudentStatsByClass(): Promise<{
        totalStudents: bigint;
        classStats: Array<ClassStats>;
    }>;
    getTotalAmountCollection(): Promise<{
        grandTotals: TotalAmountRecord;
        classTotals: Array<TotalAmountRecord>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfilePure | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markMonthPaid(admissionNumber: AdmissionNumber, month: Month): Promise<void>;
    markMonthlyPayments(admissionNumber: AdmissionNumber, payments: MonthlyPayments): Promise<void>;
    saveCallerUserProfile(profile: UserProfilePure): Promise<void>;
    searchStudent(searchQuery: string): Promise<Array<StudentAdmissionPure>>;
    getStudentInfoForParent(admissionNumber: AdmissionNumber): Promise<ParentStudentInfo | null>;
    updateStudentRecord(admissionNumber: AdmissionNumber, updatedAdmission: StudentAdmissionPure): Promise<void>;
}
import type { AdminProfilePure as _AdminProfilePure, AdmissionNumber as _AdmissionNumber, ClassName as _ClassName, ExternalBlob as _ExternalBlob, FeeExportRecord as _FeeExportRecord, FeeRecordPure as _FeeRecordPure, Gender as _Gender, Month as _Month, MonthlyPaymentPure as _MonthlyPaymentPure, StaffProfilePure as _StaffProfilePure, StudentAdmissionPersist as _StudentAdmissionPersist, StudentAdmissionPure as _StudentAdmissionPure, Time as _Time, UserProfilePure as _UserProfilePure, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmissionRecord(arg0: StudentAdmissionPure): Promise<AdmissionNumber> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmissionRecord(await to_candid_StudentAdmissionPure_n1(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmissionRecord(await to_candid_StudentAdmissionPure_n1(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createStaffAccount(arg0: Principal, arg1: Array<ClassName>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaffAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaffAccount(arg0, arg1);
            return result;
        }
    }
    async deleteStudentRecord(arg0: AdmissionNumber): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentRecord(arg0);
            return result;
        }
    }
    async getAdmission(arg0: AdmissionNumber): Promise<StudentAdmissionPure> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmission(arg0);
                return from_candid_StudentAdmissionPure_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmission(arg0);
            return from_candid_StudentAdmissionPure_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllFeesData(): Promise<Array<FeeExportRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeesData();
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeesData();
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllStudentData(): Promise<Array<StudentAdmissionPersist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentData();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentData();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getClassAdmissions(arg0: ClassName): Promise<Array<StudentAdmissionPure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassAdmissions(arg0);
                return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassAdmissions(arg0);
            return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getClassFeesData(arg0: ClassName): Promise<Array<FeeExportRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassFeesData(arg0);
                return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassFeesData(arg0);
            return from_candid_vec_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getClassStudentData(arg0: ClassName): Promise<Array<StudentAdmissionPersist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassStudentData(arg0);
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassStudentData(arg0);
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getClassWiseFeesData(arg0: ClassName): Promise<Array<ClassWiseFeesExportRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassWiseFeesData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassWiseFeesData(arg0);
            return result;
        }
    }
    async getFeeStatus(arg0: ClassName): Promise<Array<FeeRecordPure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStatus(arg0);
                return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStatus(arg0);
            return from_candid_vec_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFreeStudentsData(): Promise<Array<StudentAdmissionPersist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreeStudentsData();
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreeStudentsData();
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGenderOptions(): Promise<Array<Gender>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGenderOptions();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGenderOptions();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMonthlyFeeAlerts(): Promise<Array<PendingFeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyFeeAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyFeeAlerts();
            return result;
        }
    }
    async getPendingFeesReport(arg0: Month, arg1: ClassName | null): Promise<Array<PendingFeeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingFeesReport(arg0, to_candid_opt_n30(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingFeesReport(arg0, to_candid_opt_n30(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async getPredefinedClassOptions(): Promise<Array<ClassName>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredefinedClassOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredefinedClassOptions();
            return result;
        }
    }
    async getStudentFeeRecord(arg0: AdmissionNumber): Promise<FeeRecordPure> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentFeeRecord(arg0);
                return from_candid_FeeRecordPure_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentFeeRecord(arg0);
            return from_candid_FeeRecordPure_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStudentStatsByClass(): Promise<{
        totalStudents: bigint;
        classStats: Array<ClassStats>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentStatsByClass();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentStatsByClass();
            return result;
        }
    }
    async getTotalAmountCollection(): Promise<{
        grandTotals: TotalAmountRecord;
        classTotals: Array<TotalAmountRecord>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAmountCollection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAmountCollection();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePure | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMonthPaid(arg0: AdmissionNumber, arg1: Month): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMonthPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMonthPaid(arg0, arg1);
            return result;
        }
    }
    async markMonthlyPayments(arg0: AdmissionNumber, arg1: MonthlyPayments): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMonthlyPayments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMonthlyPayments(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfilePure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfilePure_n31(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfilePure_n31(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchStudent(arg0: string): Promise<Array<StudentAdmissionPure>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudent(arg0);
                return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudent(arg0);
            return from_candid_vec_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateStudentRecord(arg0: AdmissionNumber, arg1: StudentAdmissionPure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentRecord(arg0, await to_candid_StudentAdmissionPure_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentRecord(arg0, await to_candid_StudentAdmissionPure_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async getStudentInfoForParent(arg0: AdmissionNumber): Promise<ParentStudentInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentInfoForParent(arg0);
                if (result.length === 0) return null;
                const r = result[0] as any;
                return {
                    studentName: r.studentName,
                    fatherName: r.fatherName,
                    motherName: r.motherName,
                    admittedClass: r.admittedClass,
                    gender: from_candid_Gender_n10(this.uploadFile, this.downloadFile, r.gender),
                    dateOfBirth: r.dateOfBirth,
                    address: r.address,
                    phoneNumber: r.phoneNumber,
                    admissionDate: r.admissionDate,
                    admissionAmount: r.admissionAmount,
                    admissionNumber: r.admissionNumber,
                    isFreeStudent: r.isFreeStudent,
                    monthlyPayments: {
                        january: r.monthlyPayments.january,
                        february: r.monthlyPayments.february,
                        march: r.monthlyPayments.march,
                        april: r.monthlyPayments.april,
                        may: r.monthlyPayments.may,
                        june: r.monthlyPayments.june,
                        july: r.monthlyPayments.july,
                        august: r.monthlyPayments.august,
                        september: r.monthlyPayments.september,
                        october: r.monthlyPayments.october,
                        november: r.monthlyPayments.november,
                        december: r.monthlyPayments.december,
                    },
                };
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentInfoForParent(arg0);
            if (result.length === 0) return null;
            const r = result[0] as any;
            return {
                studentName: r.studentName,
                fatherName: r.fatherName,
                motherName: r.motherName,
                admittedClass: r.admittedClass,
                gender: from_candid_Gender_n10(this.uploadFile, this.downloadFile, r.gender),
                dateOfBirth: r.dateOfBirth,
                address: r.address,
                phoneNumber: r.phoneNumber,
                admissionDate: r.admissionDate,
                admissionAmount: r.admissionAmount,
                admissionNumber: r.admissionNumber,
                isFreeStudent: r.isFreeStudent,
                monthlyPayments: {
                    january: r.monthlyPayments.january,
                    february: r.monthlyPayments.february,
                    march: r.monthlyPayments.march,
                    april: r.monthlyPayments.april,
                    may: r.monthlyPayments.may,
                    june: r.monthlyPayments.june,
                    july: r.monthlyPayments.july,
                    august: r.monthlyPayments.august,
                    september: r.monthlyPayments.september,
                    october: r.monthlyPayments.october,
                    november: r.monthlyPayments.november,
                    december: r.monthlyPayments.december,
                },
            };
        }
    }
}
async function from_candid_ExternalBlob_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_FeeExportRecord_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeExportRecord): FeeExportRecord {
    return from_candid_record_n16(uploadFile, downloadFile, value);
}
async function from_candid_FeeRecordPure_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeRecordPure): Promise<FeeRecordPure> {
    return await from_candid_record_n28(uploadFile, downloadFile, value);
}
function from_candid_Gender_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n11(uploadFile, downloadFile, value);
}
async function from_candid_StudentAdmissionPersist_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentAdmissionPersist): Promise<StudentAdmissionPersist> {
    return await from_candid_record_n9(uploadFile, downloadFile, value);
}
async function from_candid_StudentAdmissionPure_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentAdmissionPure): Promise<StudentAdmissionPure> {
    return await from_candid_record_n9(uploadFile, downloadFile, value);
}
function from_candid_UserProfilePure_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePure): UserProfilePure {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(uploadFile, downloadFile, value);
}
async function from_candid_opt_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePure]): UserProfilePure | null {
    return value.length === 0 ? null : from_candid_UserProfilePure_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: _Month;
    paymentStatus: boolean;
    studentName: string;
    completeAddress: string;
    parentContactNumber: string;
    feeType: string;
    motherName: string;
    admissionNumber: _AdmissionNumber;
    amountPaid: bigint;
    fatherName: string;
    paymentDate: [] | [string];
    paymentMode: [] | [string];
    className: _ClassName;
}): {
    month: Month;
    paymentStatus: boolean;
    studentName: string;
    completeAddress: string;
    parentContactNumber: string;
    feeType: string;
    motherName: string;
    admissionNumber: AdmissionNumber;
    amountPaid: bigint;
    fatherName: string;
    paymentDate?: string;
    paymentMode?: string;
    className: ClassName;
} {
    return {
        month: value.month,
        paymentStatus: value.paymentStatus,
        studentName: value.studentName,
        completeAddress: value.completeAddress,
        parentContactNumber: value.parentContactNumber,
        feeType: value.feeType,
        motherName: value.motherName,
        admissionNumber: value.admissionNumber,
        amountPaid: value.amountPaid,
        fatherName: value.fatherName,
        paymentDate: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.paymentDate)),
        paymentMode: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.paymentMode)),
        className: value.className
    };
}
async function from_candid_record_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paidMonths: Array<_Month>;
    studentAdmission: _StudentAdmissionPure;
    monthlyPayments: _MonthlyPaymentPure;
}): Promise<{
    paidMonths: Array<Month>;
    studentAdmission: StudentAdmissionPure;
    monthlyPayments: MonthlyPaymentPure;
}> {
    return {
        paidMonths: value.paidMonths,
        studentAdmission: await from_candid_StudentAdmissionPure_n8(uploadFile, downloadFile, value.studentAdmission),
        monthlyPayments: value.monthlyPayments
    };
}
async function from_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentName: string;
    dateOfBirth: _Time;
    admissionDate: _Time;
    isFreeStudent: boolean;
    motherName: string;
    admissionNumber: _AdmissionNumber;
    fatherName: string;
    admittedClass: _ClassName;
    address: string;
    gender: _Gender;
    admissionAmount: bigint;
    fatherAadhaarNumber: string;
    aadhaarNumber: string;
    photo: [] | [_ExternalBlob];
    phoneNumber: string;
    motherAadhaarNumber: string;
}): Promise<{
    studentName: string;
    dateOfBirth: Time;
    admissionDate: Time;
    isFreeStudent: boolean;
    motherName: string;
    admissionNumber: AdmissionNumber;
    fatherName: string;
    admittedClass: ClassName;
    address: string;
    gender: Gender;
    admissionAmount: bigint;
    fatherAadhaarNumber: string;
    aadhaarNumber: string;
    photo?: ExternalBlob;
    phoneNumber: string;
    motherAadhaarNumber: string;
}> {
    return {
        studentName: value.studentName,
        dateOfBirth: value.dateOfBirth,
        admissionDate: value.admissionDate,
        isFreeStudent: value.isFreeStudent,
        motherName: value.motherName,
        admissionNumber: value.admissionNumber,
        fatherName: value.fatherName,
        admittedClass: value.admittedClass,
        address: value.address,
        gender: from_candid_Gender_n10(uploadFile, downloadFile, value.gender),
        admissionAmount: value.admissionAmount,
        fatherAadhaarNumber: value.fatherAadhaarNumber,
        aadhaarNumber: value.aadhaarNumber,
        photo: record_opt_to_undefined(await from_candid_opt_n12(uploadFile, downloadFile, value.photo)),
        phoneNumber: value.phoneNumber,
        motherAadhaarNumber: value.motherAadhaarNumber
    };
}
function from_candid_variant_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: _AdminProfilePure;
} | {
    staff: _StaffProfilePure;
}): {
    __kind__: "admin";
    admin: AdminProfilePure;
} | {
    __kind__: "staff";
    staff: StaffProfilePure;
} {
    return "admin" in value ? {
        __kind__: "admin",
        admin: value.admin
    } : "staff" in value ? {
        __kind__: "staff",
        staff: value.staff
    } : value;
}
function from_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeExportRecord>): Array<FeeExportRecord> {
    return value.map((x)=>from_candid_FeeExportRecord_n15(uploadFile, downloadFile, x));
}
async function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentAdmissionPersist>): Promise<Array<StudentAdmissionPersist>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StudentAdmissionPersist_n19(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentAdmissionPure>): Promise<Array<StudentAdmissionPure>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StudentAdmissionPure_n8(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeRecordPure>): Promise<Array<FeeRecordPure>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FeeRecordPure_n27(uploadFile, downloadFile, x)));
}
function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Gender>): Array<Gender> {
    return value.map((x)=>from_candid_Gender_n10(uploadFile, downloadFile, x));
}
async function to_candid_ExternalBlob_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_Gender_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n4(uploadFile, downloadFile, value);
}
async function to_candid_StudentAdmissionPure_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentAdmissionPure): Promise<_StudentAdmissionPure> {
    return await to_candid_record_n2(uploadFile, downloadFile, value);
}
function to_candid_UserProfilePure_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfilePure): _UserProfilePure {
    return to_candid_variant_n32(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(uploadFile, downloadFile, value);
}
function to_candid_opt_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassName | null): [] | [_ClassName] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentName: string;
    dateOfBirth: Time;
    admissionDate: Time;
    isFreeStudent: boolean;
    motherName: string;
    admissionNumber: AdmissionNumber;
    fatherName: string;
    admittedClass: ClassName;
    address: string;
    gender: Gender;
    admissionAmount: bigint;
    fatherAadhaarNumber: string;
    aadhaarNumber: string;
    photo?: ExternalBlob;
    phoneNumber: string;
    motherAadhaarNumber: string;
}): Promise<{
    studentName: string;
    dateOfBirth: _Time;
    admissionDate: _Time;
    isFreeStudent: boolean;
    motherName: string;
    admissionNumber: _AdmissionNumber;
    fatherName: string;
    admittedClass: _ClassName;
    address: string;
    gender: _Gender;
    admissionAmount: bigint;
    fatherAadhaarNumber: string;
    aadhaarNumber: string;
    photo: [] | [_ExternalBlob];
    phoneNumber: string;
    motherAadhaarNumber: string;
}> {
    return {
        studentName: value.studentName,
        dateOfBirth: value.dateOfBirth,
        admissionDate: value.admissionDate,
        isFreeStudent: value.isFreeStudent,
        motherName: value.motherName,
        admissionNumber: value.admissionNumber,
        fatherName: value.fatherName,
        admittedClass: value.admittedClass,
        address: value.address,
        gender: to_candid_Gender_n3(uploadFile, downloadFile, value.gender),
        admissionAmount: value.admissionAmount,
        fatherAadhaarNumber: value.fatherAadhaarNumber,
        aadhaarNumber: value.aadhaarNumber,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n5(uploadFile, downloadFile, value.photo)) : candid_none(),
        phoneNumber: value.phoneNumber,
        motherAadhaarNumber: value.motherAadhaarNumber
    };
}
function to_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "admin";
    admin: AdminProfilePure;
} | {
    __kind__: "staff";
    staff: StaffProfilePure;
}): {
    admin: _AdminProfilePure;
} | {
    staff: _StaffProfilePure;
} {
    return value.__kind__ === "admin" ? {
        admin: value.admin
    } : value.__kind__ === "staff" ? {
        staff: value.staff
    } : value;
}
function to_candid_variant_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
